version: "3.10"
services:
  app:
   build: .
   volumes:
    - .:/tododjangoapp
   ports:
    - 8000:8000
   image: docker_img_todo_list:django
   container_name: to_do_list_app
   command: gunicorn To_Do_List.wsgi:application --bind 0.0.0.0:8000


